name: 'Docker Release'

on:
  push:
    branches:
      - FanofZY-private
    paths:
      - '.github/workflows/docker-release.yml'
      - 'lib/**'
      - '!lib/**/*.test.ts'
      - 'Dockerfile'
  workflow_dispatch: {}



  release:
    runs-on: ubuntu-latest
    needs: check-env
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (x64 version)
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false  # 不推送到 Docker Hub
          tags: my-image:latest  # 可以自定义标签
          platforms: linux/amd64  # 只构建 x64 版本

      - name: Save Docker image as tar
        run: |
          docker save my-image:latest -o my-image.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v3
        with:
          name: my-image
          path: my-image.tar
